version: "3.8"

services:
  app:
    image: ghcr.io/aunghein-dev/backend_catchya:495c16b660eb3ae77ffd5d8bd2182ed820504e0c
    container_name: catch-ya
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - "127.0.0.1:8585:8080"
    networks:
      - catchya-net

  redis-server:
    image: redis:7
    container_name: redis-server
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - catchya-net

networks:
  catchya-net:
    external: true
