version: "3.8"

services:
  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - catchya-network

  app:
    image: ghcr.io/aunghein-dev/backend_catchya:d3a8bfbe94e9f7ea570c12b4bb880bc48f57db11
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - "127.0.0.1:8888:8080"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    env_file:
      - /opt/catch-ya/.env
    depends_on:
      - redis
    networks:
      - catchya-network

volumes:
  redis_data:

networks:
  catchya-network:
    driver: bridge
