version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - backend

  app:
    image: ghcr.io/aunghein-dev/backend_catchya:d3a8bfbe94e9f7ea570c12b4bb880bc48f57db11
    container_name: catch-ya
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "127.0.0.1:8888:8080"
    env_file:
      - /opt/catch-ya/.env
    networks:
      - backend

networks:
  backend:
    driver: bridge
