version: "3.8"

services:
  app:
    image: ghcr.io/aunghein-dev/backend_catchya:0ae09614620731d9e47c54095f21d65e284ff630
    container_name: catch-ya
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - "127.0.0.1:8888:8080"
    env_file:
      - /opt/catch-ya/.env
