services:
  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - catchya-network

  app:
    image: ghcr.io/aunghein-dev/backend_catchya:...
    restart: unless-stopped
    ports:
      - "127.0.0.1:8888:8080"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    env_file:
      - /opt/catch-ya/.env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - catchya-network
