name: CI/CD to Portainer (API)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

env:
  IMAGE: ghcr.io/aunghein-dev/backend_catchya

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Render compose with new tag
        run: |
          sudo apt-get update && sudo apt-get install -y gettext-base jq
          export IMAGE_TAG=${GITHUB_SHA}
          envsubst < docker-compose.prod.yml > deploy-compose.yml
          echo "---- deploy-compose.yml ----"
          sed -n '1,200p' deploy-compose.yml

      - name: Get Portainer JWT (robust)
        id: auth
        env:
          URL: ${{ secrets.PORTAINER_URL }}
          USERNAME: ${{ secrets.PORTAINER_USERNAME }}
          PASSWORD: ${{ secrets.PORTAINER_PASSWORD }}
          INSECURE_TLS: ${{ vars.PORTAINER_INSECURE_TLS }}
        run: |
          sudo apt-get update && sudo apt-get install -y jq

          # Build JSON safely (handles special characters)
          BODY=$(jq -n --arg u "$USERNAME" --arg p "$PASSWORD" '{Username:$u, Password:$p}')

          # Follow redirects; allow -k only if INSECURE_TLS=1
          CURL_OPTS="-sSL"
          if [ "$INSECURE_TLS" = "1" ]; then CURL_OPTS="$CURL_OPTS -k"; fi

          HTTP_CODE=$(curl $CURL_OPTS -o resp.json -w "%{http_code}" \
            -X POST "$URL/api/auth" \
            -H "Content-Type: application/json" \
            --data "$BODY")

          echo "Auth HTTP_CODE=$HTTP_CODE"
          echo "Auth response (first 200 chars):"
          head -c 200 resp.json || true
          echo

          if [ "$HTTP_CODE" -lt 200 ] || [ "$HTTP_CODE" -ge 300 ]; then
            echo "::error::Portainer auth failed (HTTP $HTTP_CODE). Check PORTAINER_URL, HTTPS, and creds."
            exit 1
          fi

          TOKEN=$(jq -r '.jwt // empty' < resp.json)
          if [ -z "$TOKEN" ]; then
            echo "::error::No .jwt in /api/auth response (likely HTML/redirect). Ensure /api is reachable at this URL."
            exit 1
          fi
          echo "token=$TOKEN" >> "$GITHUB_OUTPUT"
      

      - name: Update stack (redeploy)
        run: |
          BODY=$(jq -Rs '{stackFileContent: ., prune: true}' < deploy-compose.yml)
          curl -fsS -X PUT \
            "${{ secrets.PORTAINER_URL }}/api/stacks/${{ secrets.PORTAINER_STACK_ID }}?endpointId=${{ secrets.PORTAINER_ENDPOINT_ID }}" \
            -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" \
            -H "Content-Type: application/json" \
            --data-raw "${BODY}"
          echo "Stack updated."
